# Notebook 06: Đánh giá Tự động Toàn diện Hệ thống RAG (RAG Evaluation)

Notebook này thực hiện đánh giá định lượng (Quantitative Evaluation) hệ thống RAG tiếng Việt trên tập dữ liệu chuẩn `data/eval/testset.jsonl`:

1. **Nạp & Phân tích Bộ câu hỏi Benchmark** (`testset.jsonl`)
2. **Đánh giá tầng Retrieval (Tìm kiếm)**: `Hit Rate @ 1, 3, 5`, `MRR` (Mean Reciprocal Rank), `Context Recall`
3. **Đánh giá tầng Generation (Sinh câu trả lời)**: `Token F1-Score`, `Precision`, `Recall`, `Exact Match`
4. **Kiểm tra Chống Ảo Giác (Anti-Hallucination Rate)**: Đo khả năng từ chối trả lời chính xác đối với các câu hỏi ngoài phạm vi tài liệu (`is_answerable = False`)
5. **Phân tích theo Loại câu hỏi** (`direct`, `reasoning`, `unanswerable`)
6. **So sánh thử nghiệm**: Có Reranker vs Không có Reranker

## 1. Thiết lập Môi trường & Khởi tạo

In [6]:
import sys
from pathlib import Path
import pandas as pd
from IPython.display import display, Markdown

# Thiết lập đường dẫn thư mục gốc dự án
root = Path.cwd().resolve()
if root.name == "notebooks":
    root = root.parent
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

from src.config import get_config
from src.evaluation.dataset import EvaluationDataset
from src.evaluation.evaluator import RAGEvaluator
from src.pipeline.rag_pipeline import RAGPipeline

cfg = get_config(reload=True)
print(f"✅ Dự án: {root}")
print(f"⚙️  LLM Provider: {cfg.llm.default_provider} ({cfg.llm.groq.model_name})")

✅ Dự án: E:\Personal Project\vietnamese-rag
⚙️  LLM Provider: groq (openai/gpt-oss-20b)

## 2. Nạp và Khảo sát Tập Dữ liệu Testset (`testset.jsonl`)

In [2]:
testset_path = root / "data" / "eval" / "testset.jsonl"
dataset = EvaluationDataset.load_jsonl(testset_path)
df_test = dataset.to_pandas()

print(f"Tổng số câu hỏi đánh giá: {len(dataset)}")
display(df_test["question_type"].value_counts().to_frame(name="Số lượng câu"))
display(df_test.head(3)[["id", "query", "ground_truth", "question_type", "is_answerable"]])

2026-10-14 22:01:28 | INFO    | eval_dataset:load_jsonl:80 - Đã nạp thành công 50 mẫu đánh giá từ 'testset.jsonl'
Tổng số câu hỏi đánh giá: 50

               Số lượng câu
question_type
direct                   30
reasoning                10
unanswerable             10

,id,query,ground_truth,question_type,is_answerable
0,q001,Đề tài so sánh hiệu năng của hai mô hình nào t...,DenseNet-201 và EfficientNetB0.,direct,True
1,q002,Bài toán phân loại ảnh X-quang nha khoa trong ...,"5 lớp: Cavity, Fillings, Impacted Tooth, Impla...",direct,True
2,q003,Tập dữ liệu được sử dụng trong đồ án được lấy ...,Từ nền tảng Kaggle.,direct,True

## 3. Khởi tạo Pipeline & Thực thi Đánh giá Toàn diện

In [3]:
pipeline = RAGPipeline()
evaluator = RAGEvaluator(pipeline=pipeline)

2026-10-14 22:01:51 | INFO    | embedder:__init__:39 - Đang tải Embedding model: BAAI/bge-m3 trên thiết bị: cpu

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

2026-10-14 22:02:00 | INFO    | embedder:__init__:49 - Tải model BAAI/bge-m3 thành công. Kích thước vector: 1024
2026-10-14 22:02:00 | INFO    | groq_llm:__init__:34 - Khởi tạo Groq LLM với mô hình: openai/gpt-oss-120b
2026-10-14 22:02:00 | INFO    | prompt_builder:_load_template:47 - Đã nạp prompt template từ: qa_prompt.yaml
2026-10-14 22:02:00 | INFO    | rag_evaluator:__init__:112 - RAGEvaluator sử dụng template: eval_prompt.yaml
2026-10-14 22:02:00 | INFO    | prompt_builder:_load_template:47 - Đã nạp prompt template từ: eval_prompt.yaml
2026-10-14 22:02:01 | INFO    | llm_judge:__init__:63 - Đã khởi tạo LLM Judge với model: openai/gpt-oss-120b

In [3]:
q025 = "Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?"
result1 = pipeline.query(q025, top_k=6, top_n=3)

2026-10-14 15:49:50 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?'
2026-10-14 15:49:50 | INFO    | retrieval_pipeline:retrieve:59 - Retrieval Pipeline cho query: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?' (hybrid=False, rerank=True, top_k=6, top_n=3)
2026-10-14 15:49:50 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?' (top_k=6)

The `sentences` argument was renamed and is now deprecated. Please use `inputs` instead.

2026-10-14 15:49:50 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 6 chunks tương đồng từ Qdrant.
2026-10-14 15:49:50 | INFO    | reranker:rerank:61 - Bắt đầu Reranking cho 6 chunks với câu hỏi: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?' (top_n=3)
2026-10-14 15:49:57 | INFO    | reranker:rerank:85 - Hoàn tất Reranking. Lọc lại top 3 chunks chất lượng nhất.
2026-10-14 15:49:57 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?'
2026-10-14 15:49:59 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 9.58s

In [4]:
# # Thực hiện đánh giá (Bật đầy đủ Hybrid + Reranker)
result = evaluator.evaluate(
    dataset=dataset,
    # top_k=6,
    # top_n=4,
    use_rerank=True,
    use_hybrid=False,
)

result.print_summary()

2026-10-14 22:02:05 | INFO    | rag_evaluator:evaluate:151 - Bắt đầu đánh giá RAG trên 50 câu hỏi...

Evaluating RAG:   0%|          | 0/50 [00:00<?, ?query/s]

2026-10-14 22:02:05 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Đề tài so sánh hiệu năng của hai mô hình nào trong bài toán phân loại bệnh lý trên răng qua ảnh X-quang?'
2026-10-14 22:02:05 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:02:05 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Đề tài so sánh hiệu năng của hai mô hình nào trong bài toán phân loại bệnh lý trên răng qua ảnh X-quang?' (top_k=10)

The `sentences` argument was renamed and is now deprecated. Please use `inputs` instead.

2026-10-14 22:02:06 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:02:06 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:02:06 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:02:06 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:02:06 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Đề tài so sánh hiệu năng của hai mô hình nào trong bài toán phân loại bệnh lý trên răng qua ảnh X-quang?'
2026-10-14 22:02:08 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 2.93s

Evaluating RAG:   2%|▏         | 1/50 [00:04<03:46,  4.62s/query]

2026-10-14 22:02:10 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Bài toán phân loại ảnh X-quang nha khoa trong đồ án gồm bao nhiêu lớp và đó là những lớp nào?'
2026-10-14 22:02:10 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:02:10 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Bài toán phân loại ảnh X-quang nha khoa trong đồ án gồm bao nhiêu lớp và đó là những lớp nào?' (top_k=10)
2026-10-14 22:02:10 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:02:10 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:02:10 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:02:10 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:02:10 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Bài toán phân loại ảnh X-quang nha khoa trong đồ án gồm bao nhiêu lớp và đó là những lớp nào?'
2026-10-14 22:02:11 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 1.14s

Evaluating RAG:   4%|▍         | 2/50 [00:07<03:01,  3.78s/query]

2026-10-14 22:02:13 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Tập dữ liệu được sử dụng trong đồ án được lấy từ nguồn nào?'
2026-10-14 22:02:13 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:02:13 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Tập dữ liệu được sử dụng trong đồ án được lấy từ nguồn nào?' (top_k=10)
2026-10-14 22:02:13 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:02:13 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:02:13 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:02:13 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:02:13 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Tập dữ liệu được sử dụng trong đồ án được lấy từ nguồn nào?'
2026-10-14 22:02:15 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 2.52s

Evaluating RAG:   6%|▌         | 3/50 [00:11<02:55,  3.73s/query]

2026-10-14 22:02:16 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Số lượng ảnh trong tập train, valid và test của bộ dữ liệu là bao nhiêu?'
2026-10-14 22:02:16 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:02:16 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Số lượng ảnh trong tập train, valid và test của bộ dữ liệu là bao nhiêu?' (top_k=10)
2026-10-14 22:02:17 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:02:17 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:02:17 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:02:17 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:02:17 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Số lượng ảnh trong tập train, valid và test của bộ dữ liệu là bao nhiêu?'
2026-10-14 22:02:18 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 1.58s

Evaluating RAG:   8%|▊         | 4/50 [00:14<02:46,  3.63s/query]

2026-10-14 22:02:20 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Kiến trúc DenseNet201 được chia thành bao nhiêu Dense Block?'
2026-10-14 22:02:20 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:02:20 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Kiến trúc DenseNet201 được chia thành bao nhiêu Dense Block?' (top_k=10)
2026-10-14 22:02:20 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:02:20 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:02:20 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:02:20 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:02:20 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Kiến trúc DenseNet201 được chia thành bao nhiêu Dense Block?'
2026-10-14 22:02:30 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 10.10s

Evaluating RAG:  10%|█         | 5/50 [00:30<06:02,  8.05s/query]

2026-10-14 22:02:36 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Growth Rate (k) thường dùng trong DenseNet201 của đồ án là bao nhiêu?'
2026-10-14 22:02:36 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:02:36 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Growth Rate (k) thường dùng trong DenseNet201 của đồ án là bao nhiêu?' (top_k=10)
2026-10-14 22:02:36 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:02:36 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:02:36 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:02:36 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:02:36 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Growth Rate (k) thường dùng trong DenseNet201 của đồ án là bao nhiêu?'
2026-10-14 22:02:49 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 13.53s

Evaluating RAG:  12%|█▏        | 6/50 [00:48<08:24, 11.46s/query]

2026-10-14 22:02:54 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Mô hình nào đạt độ chính xác trên tập test cao hơn và cao hơn bao nhiêu?'
2026-10-14 22:02:54 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:02:54 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Mô hình nào đạt độ chính xác trên tập test cao hơn và cao hơn bao nhiêu?' (top_k=10)
2026-10-14 22:02:54 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:02:54 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:02:54 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:02:54 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:02:54 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Mô hình nào đạt độ chính xác trên tập test cao hơn và cao hơn bao nhiêu?'
2026-10-14 22:03:08 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 14.06s

Evaluating RAG:  14%|█▍        | 7/50 [01:12<11:07, 15.53s/query]

2026-10-14 22:03:18 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Mô hình DenseNet201 đạt kết quả tốt nhất tại epoch thứ bao nhiêu?'
2026-10-14 22:03:18 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:03:18 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Mô hình DenseNet201 đạt kết quả tốt nhất tại epoch thứ bao nhiêu?' (top_k=10)
2026-10-14 22:03:18 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:03:18 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:03:18 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:03:18 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:03:18 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Mô hình DenseNet201 đạt kết quả tốt nhất tại epoch thứ bao nhiêu?'
2026-10-14 22:03:30 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 12.44s

Evaluating RAG:  16%|█▌        | 8/50 [01:37<12:57, 18.51s/query]

2026-10-14 22:03:43 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Phương pháp tiền xử lý ảnh đơn lẻ nào có tỷ lệ sửa đúng cao nhất trên 120 mẫu lỗi?'
2026-10-14 22:03:43 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:03:43 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Phương pháp tiền xử lý ảnh đơn lẻ nào có tỷ lệ sửa đúng cao nhất trên 120 mẫu lỗi?' (top_k=10)
2026-10-14 22:03:43 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:03:43 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:03:43 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:03:43 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:03:43 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Phương pháp tiền xử lý ảnh đơn lẻ nào có tỷ lệ sửa đúng cao nhất trên 120 mẫu lỗi?'
2026-10-14 22:03:54 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 11.63s

Evaluating RAG:  18%|█▊        | 9/50 [02:02<13:56, 20.40s/query]

2026-10-14 22:04:07 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Vì sao nhóm nghiên cứu chọn DenseNet201 làm mô hình cốt lõi thay vì EfficientNetB0?'
2026-10-14 22:04:07 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:04:07 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Vì sao nhóm nghiên cứu chọn DenseNet201 làm mô hình cốt lõi thay vì EfficientNetB0?' (top_k=10)
2026-10-14 22:04:07 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:04:07 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:04:07 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:04:07 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:04:07 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Vì sao nhóm nghiên cứu chọn DenseNet201 làm mô hình cốt lõi thay vì EfficientNetB0?'
2026-10-14 22:04:10 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 2.79s

Evaluating RAG:  20%|██        | 10/50 [02:14<11:59, 17.98s/query]

2026-10-14 22:04:20 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Vì sao lớp Normal trong bài toán phân loại răng miệng lại có kết quả nhận diện tốt nhất?'
2026-10-14 22:04:20 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:04:20 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Vì sao lớp Normal trong bài toán phân loại răng miệng lại có kết quả nhận diện tốt nhất?' (top_k=10)
2026-10-14 22:04:20 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:04:20 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:04:20 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:04:20 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:04:20 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Vì sao lớp Normal trong bài toán phân loại răng miệng lại có kết quả nhận diện tốt nhất?'
2026-10-14 22:04:34 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 14.30s

Evaluating RAG:  22%|██▏       | 11/50 [02:46<14:26, 22.21s/query]

2026-10-14 22:04:52 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Vì sao giải pháp Ensemble by Class lại cải thiện kết quả phân loại tốt hơn so với chỉ dùng một phương pháp tiền xử lý đơn lẻ?'
2026-10-14 22:04:52 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:04:52 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Vì sao giải pháp Ensemble by Class lại cải thiện kết quả phân loại tốt hơn so với chỉ dùng một phương pháp tiền xử lý đơn lẻ?' (top_k=10)
2026-10-14 22:04:52 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:04:52 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:04:52 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:04:52 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:04:52 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Vì sao giải pháp Ensemble by Class lại cải thiện kết quả phân loại tốt hơn so với chỉ dùng một phương pháp tiền xử lý đơn lẻ?'
2026-10-14 22:04:55 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 3.01s

Evaluating RAG:  24%|██▍       | 12/50 [02:57<11:50, 18.70s/query]

2026-10-14 22:05:02 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Bệnh nhân trong tập dữ liệu X-quang nha khoa thuộc độ tuổi nào?'
2026-10-14 22:05:02 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:05:02 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Bệnh nhân trong tập dữ liệu X-quang nha khoa thuộc độ tuổi nào?' (top_k=10)
2026-10-14 22:05:02 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:05:02 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:05:02 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:05:02 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:05:02 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Bệnh nhân trong tập dữ liệu X-quang nha khoa thuộc độ tuổi nào?'
2026-10-14 22:05:18 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 16.19s

Evaluating RAG:  26%|██▌       | 13/50 [03:15<11:20, 18.40s/query]

2026-10-14 22:05:20 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Mô hình DenseNet201 có được triển khai trên thiết bị di động không?'
2026-10-14 22:05:20 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:05:20 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Mô hình DenseNet201 có được triển khai trên thiết bị di động không?' (top_k=10)
2026-10-14 22:05:20 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:05:20 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:05:20 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:05:20 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:05:20 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Mô hình DenseNet201 có được triển khai trên thiết bị di động không?'
2026-10-14 22:05:37 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 17.47s

Evaluating RAG:  28%|██▊       | 14/50 [03:36<11:40, 19.47s/query]

2026-10-14 22:05:42 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Chi phí huấn luyện mô hình trên nền tảng Kaggle là bao nhiêu?'
2026-10-14 22:05:42 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:05:42 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Chi phí huấn luyện mô hình trên nền tảng Kaggle là bao nhiêu?' (top_k=10)
2026-10-14 22:05:42 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:05:42 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:05:42 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:05:42 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:05:42 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Chi phí huấn luyện mô hình trên nền tảng Kaggle là bao nhiêu?'
2026-10-14 22:05:51 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 9.35s

Evaluating RAG:  30%|███       | 15/50 [03:49<10:05, 17.29s/query]

2026-10-14 22:05:54 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Đồ án khai phá dữ liệu sử dụng hai tập dữ liệu chính nào?'
2026-10-14 22:05:54 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:05:54 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Đồ án khai phá dữ liệu sử dụng hai tập dữ liệu chính nào?' (top_k=10)
2026-10-14 22:05:54 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:05:54 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:05:54 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:05:54 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:05:54 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Đồ án khai phá dữ liệu sử dụng hai tập dữ liệu chính nào?'
2026-10-14 22:06:06 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 11.49s

Evaluating RAG:  32%|███▏      | 16/50 [04:02<09:03, 15.99s/query]

2026-10-14 22:06:07 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Tập dữ liệu Fitness_Membership_Analytics_Dataset.csv có bao nhiêu bản ghi và bao nhiêu cột?'
2026-10-14 22:06:07 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:06:07 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Tập dữ liệu Fitness_Membership_Analytics_Dataset.csv có bao nhiêu bản ghi và bao nhiêu cột?' (top_k=10)
2026-10-14 22:06:07 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:06:07 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:06:07 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:06:07 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:06:07 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Tập dữ liệu Fitness_Membership_Analytics_Dataset.csv có bao nhiêu bản ghi và bao nhiêu cột?'
2026-10-14 22:06:24 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 17.10s

Evaluating RAG:  34%|███▍      | 17/50 [04:21<09:23, 17.07s/query]

2026-10-14 22:06:27 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Tập dữ liệu Customer Shopping Behavior.csv có bao nhiêu hàng và bao nhiêu cột?'
2026-10-14 22:06:27 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:06:27 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Tập dữ liệu Customer Shopping Behavior.csv có bao nhiêu hàng và bao nhiêu cột?' (top_k=10)
2026-10-14 22:06:27 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:06:27 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:06:27 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:06:27 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:06:27 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Tập dữ liệu Customer Shopping Behavior.csv có bao nhiêu hàng và bao nhiêu cột?'
2026-10-14 22:06:40 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 13.09s

Evaluating RAG:  36%|███▌      | 18/50 [04:42<09:45, 18.28s/query]

2026-10-14 22:06:48 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Số cụm tối ưu được chọn cho bài toán phân cụm khách hàng Fitness là bao nhiêu?'
2026-10-14 22:06:48 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:06:48 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Số cụm tối ưu được chọn cho bài toán phân cụm khách hàng Fitness là bao nhiêu?' (top_k=10)
2026-10-14 22:06:48 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:06:48 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:06:48 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:06:48 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:06:48 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Số cụm tối ưu được chọn cho bài toán phân cụm khách hàng Fitness là bao nhiêu?'
2026-10-14 22:07:04 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 16.11s

Evaluating RAG:  38%|███▊      | 19/50 [05:03<09:44, 18.84s/query]

2026-10-14 22:07:08 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Thuật toán nào được chọn cho bài toán phân cụm khách hàng Fitness?'
2026-10-14 22:07:08 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:07:08 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Thuật toán nào được chọn cho bài toán phân cụm khách hàng Fitness?' (top_k=10)
2026-10-14 22:07:08 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:07:08 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:07:08 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:07:08 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:07:08 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Thuật toán nào được chọn cho bài toán phân cụm khách hàng Fitness?'
2026-10-14 22:07:20 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 11.55s

Evaluating RAG:  40%|████      | 20/50 [05:25<09:59, 19.98s/query]

2026-10-14 22:07:31 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Chỉ số Silhouette của mô hình K-Means trên tập Fitness là bao nhiêu?'
2026-10-14 22:07:31 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:07:31 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Chỉ số Silhouette của mô hình K-Means trên tập Fitness là bao nhiêu?' (top_k=10)
2026-10-14 22:07:31 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:07:31 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:07:31 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:07:31 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:07:31 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Chỉ số Silhouette của mô hình K-Means trên tập Fitness là bao nhiêu?'
2026-10-14 22:07:39 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 7.95s

Evaluating RAG:  42%|████▏     | 21/50 [05:39<08:49, 18.27s/query]

2026-10-14 22:07:45 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Mô hình nào tốt nhất cho bài toán phân loại churn của hội viên Fitness theo F1-Score?'
2026-10-14 22:07:45 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:07:45 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Mô hình nào tốt nhất cho bài toán phân loại churn của hội viên Fitness theo F1-Score?' (top_k=10)
2026-10-14 22:07:45 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:07:45 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:07:45 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:07:45 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:07:45 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Mô hình nào tốt nhất cho bài toán phân loại churn của hội viên Fitness theo F1-Score?'
2026-10-14 22:07:58 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 12.87s

Evaluating RAG:  44%|████▍     | 22/50 [05:58<08:32, 18.30s/query]

2026-10-14 22:08:03 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Số cụm tối ưu cho bài toán phân cụm khách hàng Shopping là bao nhiêu?'
2026-10-14 22:08:03 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:08:03 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Số cụm tối ưu cho bài toán phân cụm khách hàng Shopping là bao nhiêu?' (top_k=10)
2026-10-14 22:08:03 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:08:03 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:08:03 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:08:03 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:08:03 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Số cụm tối ưu cho bài toán phân cụm khách hàng Shopping là bao nhiêu?'
2026-10-14 22:08:14 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 10.65s

Evaluating RAG:  46%|████▌     | 23/50 [06:15<08:01, 17.83s/query]

2026-10-14 22:08:20 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Mô hình nào tốt nhất cho bài toán phân loại khách hàng tiềm năng trong tập dữ liệu Shopping?'
2026-10-14 22:08:20 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:08:20 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Mô hình nào tốt nhất cho bài toán phân loại khách hàng tiềm năng trong tập dữ liệu Shopping?' (top_k=10)
2026-10-14 22:08:20 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:08:20 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:08:20 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:08:20 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:08:20 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Mô hình nào tốt nhất cho bài toán phân loại khách hàng tiềm năng trong tập dữ liệu Shopping?'
2026-10-14 22:08:33 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 12.60s

Evaluating RAG:  48%|████▊     | 24/50 [06:33<07:49, 18.07s/query]

2026-10-14 22:08:39 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?'
2026-10-14 22:08:39 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:08:39 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?' (top_k=10)
2026-10-14 22:08:39 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:08:39 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:08:39 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:08:39 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:08:39 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Vì sao K-Means được chọn thay vì HAC cho bài toán phân cụm khách hàng Fitness?'
2026-10-14 22:08:51 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 12.03s

Evaluating RAG:  50%|█████     | 25/50 [06:51<07:27, 17.90s/query]

2026-10-14 22:08:56 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Dựa trên phân tích EDA, vì sao không nên phụ thuộc vào giảm giá để tăng tần suất mua hàng?'
2026-10-14 22:08:56 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:08:56 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Dựa trên phân tích EDA, vì sao không nên phụ thuộc vào giảm giá để tăng tần suất mua hàng?' (top_k=10)
2026-10-14 22:08:56 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:08:56 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:08:56 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:08:56 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:08:56 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Dựa trên phân tích EDA, vì sao không nên phụ thuộc vào giảm giá để tăng tần suất mua hàng?'
2026-10-14 22:09:12 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 15.85s

Evaluating RAG:  52%|█████▏    | 26/50 [07:11<07:26, 18.59s/query]

2026-10-14 22:09:16 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Vì sao nhóm nghiên cứu tạo đặc trưng Spend per Purchase trong bài toán phân loại khách hàng tiềm năng?'
2026-10-14 22:09:16 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:09:16 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Vì sao nhóm nghiên cứu tạo đặc trưng Spend per Purchase trong bài toán phân loại khách hàng tiềm năng?' (top_k=10)
2026-10-14 22:09:17 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:09:17 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:09:17 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:09:17 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:09:17 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Vì sao nhóm nghiên cứu tạo đặc trưng Spend per Purchase trong bài toán phân loại khách hàng tiềm năng?'
2026-10-14 22:09:31 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 14.25s

Evaluating RAG:  54%|█████▍    | 27/50 [07:33<07:30, 19.60s/query]

2026-10-14 22:09:38 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Tên thương hiệu của chuỗi phòng gym trong tập dữ liệu Fitness là gì?'
2026-10-14 22:09:38 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:09:38 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Tên thương hiệu của chuỗi phòng gym trong tập dữ liệu Fitness là gì?' (top_k=10)
2026-10-14 22:09:38 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:09:38 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:09:38 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:09:38 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:09:38 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Tên thương hiệu của chuỗi phòng gym trong tập dữ liệu Fitness là gì?'
2026-10-14 22:09:51 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 12.87s

Evaluating RAG:  56%|█████▌    | 28/50 [07:50<06:55, 18.88s/query]

2026-10-14 22:09:56 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Tập dữ liệu Customer Shopping Behavior được thu thập trong khoảng thời gian nào?'
2026-10-14 22:09:56 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:09:56 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Tập dữ liệu Customer Shopping Behavior được thu thập trong khoảng thời gian nào?' (top_k=10)
2026-10-14 22:09:56 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:09:56 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:09:56 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:09:56 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:09:56 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Tập dữ liệu Customer Shopping Behavior được thu thập trong khoảng thời gian nào?'
2026-10-14 22:10:10 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 14.69s

Evaluating RAG:  58%|█████▊    | 29/50 [08:09<06:38, 18.98s/query]

2026-10-14 22:10:15 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Doanh thu chính xác của chuỗi phòng gym trong năm 2024 là bao nhiêu?'
2026-10-14 22:10:15 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:10:15 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Doanh thu chính xác của chuỗi phòng gym trong năm 2024 là bao nhiêu?' (top_k=10)
2026-10-14 22:10:15 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:10:15 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:10:15 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:10:15 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:10:15 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Doanh thu chính xác của chuỗi phòng gym trong năm 2024 là bao nhiêu?'
2026-10-14 22:10:24 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 8.82s

Evaluating RAG:  60%|██████    | 30/50 [08:26<06:03, 18.17s/query]

2026-10-14 22:10:31 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?'
2026-10-14 22:10:31 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:10:31 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?' (top_k=10)
2026-10-14 22:10:31 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:10:31 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:10:31 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:10:31 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:10:31 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?'
2026-10-14 22:10:37 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 6.41s

Evaluating RAG:  62%|██████▏   | 31/50 [08:39<05:20, 16.87s/query]

2026-10-14 22:10:45 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?'
2026-10-14 22:10:45 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:10:45 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?' (top_k=10)
2026-10-14 22:10:45 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:10:45 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:10:45 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:10:45 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:10:45 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?'
2026-10-14 22:10:54 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 8.67s

Evaluating RAG:  64%|██████▍   | 32/50 [08:53<04:45, 15.84s/query]

2026-10-14 22:10:58 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?'
2026-10-14 22:10:58 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:10:58 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?' (top_k=10)
2026-10-14 22:10:58 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:10:58 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:10:58 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:10:58 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:10:58 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?'
2026-10-14 22:11:11 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 12.37s

Evaluating RAG:  66%|██████▌   | 33/50 [09:08<04:25, 15.62s/query]

2026-10-14 22:11:13 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Trong bảng tham số mô hình DenseNet201, kích thước ảnh đầu vào (IMG_SIZE) được thiết lập là bao nhiêu?, Vì sao tác giả lại chọn kích thước như vậy thay vì kích thước như thiết kế ban đầu của kiến trúc?'
2026-10-14 22:11:13 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:11:13 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Trong bảng tham số mô hình DenseNet201, kích thước ảnh đầu vào (IMG_SIZE) được thiết lập là bao nhiêu?, Vì sao tác giả lại chọn kích thước như vậy thay vì kích thước như thiết kế ban đầu của kiến trúc?' (top_k=10)
2026-10-14 22:11:14 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:11:14 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:11:14 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:11:14 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:11:14 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Trong bảng tham số mô hình DenseNet201, kích thước ảnh đầu vào (IMG_SIZE) được thiết lập là bao nhiêu?, Vì sao tác giả lại chọn kích thước như vậy thay vì kích thước như thiết kế ban đầu của kiến trúc?'
2026-10-14 22:11:28 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 15.03s

Evaluating RAG:  68%|██████▊   | 34/50 [09:30<04:43, 17.70s/query]

2026-10-14 22:11:36 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Phương pháp tiền xử lý ảnh nào có tỷ lệ chính xác thấp nhất trong 10 phương pháp được thử nghiệm?'
2026-10-14 22:11:36 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:11:36 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Phương pháp tiền xử lý ảnh nào có tỷ lệ chính xác thấp nhất trong 10 phương pháp được thử nghiệm?' (top_k=10)
2026-10-14 22:11:36 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:11:36 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:11:36 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:11:36 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:11:36 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Phương pháp tiền xử lý ảnh nào có tỷ lệ chính xác thấp nhất trong 10 phương pháp được thử nghiệm?'
2026-10-14 22:11:48 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 11.75s

Evaluating RAG:  70%|███████   | 35/50 [10:05<05:41, 22.78s/query]

2026-10-14 22:12:11 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Theo Bảng 5, mô hình EfficientNetB0 đạt val_loss tốt nhất tại epoch nào và giá trị cụ thể là bao nhiêu?'
2026-10-14 22:12:11 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:12:11 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo Bảng 5, mô hình EfficientNetB0 đạt val_loss tốt nhất tại epoch nào và giá trị cụ thể là bao nhiêu?' (top_k=10)
2026-10-14 22:12:11 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:12:11 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:12:11 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:12:11 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:12:11 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Theo Bảng 5, mô hình EfficientNetB0 đạt val_loss tốt nhất tại epoch nào và giá trị cụ thể là bao nhiêu?'
2026-10-14 22:12:14 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 3.85s

Evaluating RAG:  72%|███████▏  | 36/50 [10:12<04:10, 17.92s/query]

2026-10-14 22:12:17 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.'
2026-10-14 22:12:17 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:12:17 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.' (top_k=10)
2026-10-14 22:12:17 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:12:17 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:12:17 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:12:17 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:12:17 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.'
2026-10-14 22:12:19 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 2.25s

Evaluating RAG:  74%|███████▍  | 37/50 [10:26<03:39, 16.85s/query]

2026-10-14 22:12:31 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Từ Bảng 1 (phân bố dữ liệu) và Bảng 6 (các độ đo), giải thích tại sao lớp Impacted Tooth có Recall 0.75 nhưng F1-Score chỉ đạt 0.62?'
2026-10-14 22:12:31 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:12:31 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Từ Bảng 1 (phân bố dữ liệu) và Bảng 6 (các độ đo), giải thích tại sao lớp Impacted Tooth có Recall 0.75 nhưng F1-Score chỉ đạt 0.62?' (top_k=10)
2026-10-14 22:12:32 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:12:32 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:12:32 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:12:32 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:12:32 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Từ Bảng 1 (phân bố dữ liệu) và Bảng 6 (các độ đo), giải thích tại sao lớp Impacted Tooth có Recall 0.75 nhưng F1-Score chỉ đạt 0.62?'
2026-10-14 22:12:42 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 10.57s

Evaluating RAG:  76%|███████▌  | 38/50 [10:48<03:39, 18.28s/query]

2026-10-14 22:12:53 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Độ tuổi trung bình của bệnh nhân trong từng lớp?'
2026-10-14 22:12:53 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:12:53 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Độ tuổi trung bình của bệnh nhân trong từng lớp?' (top_k=10)
2026-10-14 22:12:53 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:12:53 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:12:53 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:12:53 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:12:53 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Độ tuổi trung bình của bệnh nhân trong từng lớp?'
2026-10-14 22:13:09 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 16.14s

Evaluating RAG:  78%|███████▊  | 39/50 [11:05<03:18, 18.08s/query]

2026-10-14 22:13:11 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Bảng 4 và Bảng 5 có ghi chi tiết cấu hình GPU (tên GPU, VRAM) sử dụng cho từng epoch không?'
2026-10-14 22:13:11 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:13:11 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Bảng 4 và Bảng 5 có ghi chi tiết cấu hình GPU (tên GPU, VRAM) sử dụng cho từng epoch không?' (top_k=10)
2026-10-14 22:13:11 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:13:11 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:13:11 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:13:11 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:13:11 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Bảng 4 và Bảng 5 có ghi chi tiết cấu hình GPU (tên GPU, VRAM) sử dụng cho từng epoch không?'
2026-10-14 22:13:26 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 15.20s

Evaluating RAG:  80%|████████  | 40/50 [11:25<03:06, 18.70s/query]

2026-10-14 22:13:31 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Theo Bảng 1 (mô tả các cột trong tập dữ liệu Fitness), cột nào ghi giá gói sau khi điều chỉnh theo chu kỳ thanh toán?'
2026-10-14 22:13:31 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:13:31 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo Bảng 1 (mô tả các cột trong tập dữ liệu Fitness), cột nào ghi giá gói sau khi điều chỉnh theo chu kỳ thanh toán?' (top_k=10)
2026-10-14 22:13:31 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:13:31 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:13:31 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:13:31 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:13:31 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Theo Bảng 1 (mô tả các cột trong tập dữ liệu Fitness), cột nào ghi giá gói sau khi điều chỉnh theo chu kỳ thanh toán?'
2026-10-14 22:13:42 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 11.63s

Evaluating RAG:  82%|████████▏ | 41/50 [11:38<02:32, 16.93s/query]

2026-10-14 22:13:44 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?'
2026-10-14 22:13:44 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:13:44 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?' (top_k=10)
2026-10-14 22:13:44 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:13:44 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:13:44 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:13:44 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:13:44 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?'
2026-10-14 22:13:54 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 9.97s

Evaluating RAG:  84%|████████▍ | 42/50 [11:55<02:14, 16.80s/query]

2026-10-14 22:14:00 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Chi nhánh phòng gym nào có tổng doanh thu cao nhất trong hệ thống và giá trị cụ thể là bao nhiêu USD/tháng?'
2026-10-14 22:14:00 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:14:00 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Chi nhánh phòng gym nào có tổng doanh thu cao nhất trong hệ thống và giá trị cụ thể là bao nhiêu USD/tháng?' (top_k=10)
2026-10-14 22:14:00 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:14:00 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:14:00 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:14:00 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:14:00 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Chi nhánh phòng gym nào có tổng doanh thu cao nhất trong hệ thống và giá trị cụ thể là bao nhiêu USD/tháng?'
2026-10-14 22:14:14 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 14.00s

Evaluating RAG:  86%|████████▌ | 43/50 [12:15<02:03, 17.71s/query]

2026-10-14 22:14:20 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?'
2026-10-14 22:14:20 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:14:20 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?' (top_k=10)
2026-10-14 22:14:20 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:14:20 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:14:20 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:14:20 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:14:20 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?'
2026-10-14 22:14:37 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 17.26s

Evaluating RAG:  88%|████████▊ | 44/50 [12:38<01:55, 19.32s/query]

2026-10-14 22:14:43 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Theo kết quả HyperParameter Tuning ở Chương 3, XGBoost đạt F1-Score bao nhiêu trong bài toán phân loại khách hàng tiềm năng trên tập Shopping?'
2026-10-14 22:14:43 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:14:43 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo kết quả HyperParameter Tuning ở Chương 3, XGBoost đạt F1-Score bao nhiêu trong bài toán phân loại khách hàng tiềm năng trên tập Shopping?' (top_k=10)
2026-10-14 22:14:43 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:14:43 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:14:43 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:14:43 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:14:43 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Theo kết quả HyperParameter Tuning ở Chương 3, XGBoost đạt F1-Score bao nhiêu trong bài toán phân loại khách hàng tiềm năng trên tập Shopping?'
2026-10-14 22:14:58 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 15.22s

Evaluating RAG:  90%|█████████ | 45/50 [12:55<01:34, 18.83s/query]

2026-10-14 22:15:01 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Theo Bảng 2, chỉ số Davies-Bouldin của mô hình K-Means trên tập Fitness là bao nhiêu?'
2026-10-14 22:15:01 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:15:01 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo Bảng 2, chỉ số Davies-Bouldin của mô hình K-Means trên tập Fitness là bao nhiêu?' (top_k=10)
2026-10-14 22:15:01 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:15:01 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:15:01 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:15:01 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:15:01 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Theo Bảng 2, chỉ số Davies-Bouldin của mô hình K-Means trên tập Fitness là bao nhiêu?'
2026-10-14 22:15:18 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 17.37s

Evaluating RAG:  92%|█████████▏| 46/50 [13:14<01:14, 18.71s/query]

2026-10-14 22:15:19 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Dựa vào Bảng 5, giải thích tại sao Random Forest được chọn là mô hình tối ưu cho bài toán churn dù XGBoost có ROC-AUC cao hơn.'
2026-10-14 22:15:19 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:15:19 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Dựa vào Bảng 5, giải thích tại sao Random Forest được chọn là mô hình tối ưu cho bài toán churn dù XGBoost có ROC-AUC cao hơn.' (top_k=10)
2026-10-14 22:15:19 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:15:19 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:15:19 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:15:19 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:15:19 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Dựa vào Bảng 5, giải thích tại sao Random Forest được chọn là mô hình tối ưu cho bài toán churn dù XGBoost có ROC-AUC cao hơn.'
2026-10-14 22:15:33 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 14.14s

Evaluating RAG:  94%|█████████▍| 47/50 [13:34<00:57, 19.15s/query]

2026-10-14 22:15:39 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Theo phân tích tại mục 2.4.2, vì sao thâm niên hội viên (Tenure) không tương quan với tần suất tập luyện lại là chỉ dấu quan trọng cho bài toán dự báo churn?'
2026-10-14 22:15:39 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:15:39 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo phân tích tại mục 2.4.2, vì sao thâm niên hội viên (Tenure) không tương quan với tần suất tập luyện lại là chỉ dấu quan trọng cho bài toán dự báo churn?' (top_k=10)
2026-10-14 22:15:40 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:15:40 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:15:40 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:15:40 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:15:40 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Theo phân tích tại mục 2.4.2, vì sao thâm niên hội viên (Tenure) không tương quan với tần suất tập luyện lại là chỉ dấu quan trọng cho bài toán dự báo churn?'
2026-10-14 22:15:51 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 11.98s

Evaluating RAG:  96%|█████████▌| 48/50 [13:54<00:38, 19.42s/query]

2026-10-14 22:15:59 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Dựa vào bảng 1 mô tả cột trong tập dữ liệu Fitness ngày sinh trung bình của hội viên là bao nhiêu ?'
2026-10-14 22:15:59 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:15:59 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Dựa vào bảng 1 mô tả cột trong tập dữ liệu Fitness ngày sinh trung bình của hội viên là bao nhiêu ?' (top_k=10)
2026-10-14 22:16:00 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:16:00 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:16:00 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:16:00 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:16:00 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Dựa vào bảng 1 mô tả cột trong tập dữ liệu Fitness ngày sinh trung bình của hội viên là bao nhiêu ?'
2026-10-14 22:16:13 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 13.47s

Evaluating RAG:  98%|█████████▊| 49/50 [14:11<00:18, 18.82s/query]

2026-10-14 22:16:17 | INFO    | rag_pipeline:query:45 - Bắt đầu chu trình RAG Pipeline cho câu hỏi: 'Trong tập dữ liệu Customer Shopping Behavior, có cột nào ghi thông tin về số điện thoại của khách hàng không?'
2026-10-14 22:16:17 | INFO    | retrieval_pipeline:retrieve:107 - Retrieval Pipeline | hybrid=False | rerank=True | candidate_k=10 | final_n=5
2026-10-14 22:16:17 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Trong tập dữ liệu Customer Shopping Behavior, có cột nào ghi thông tin về số điện thoại của khách hàng không?' (top_k=10)
2026-10-14 22:16:17 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-14 22:16:17 | INFO    | retrieval_pipeline:retrieve:128 - Candidate Retrieval tra ve 10 chunks.
2026-10-14 22:16:17 | WARNING | retrieval_pipeline:retrieve:157 - Reranker không khả dụng; Giữ các chunk từ retrieval ban đầu.
2026-10-14 22:16:17 | INFO    | retrieval_pipeline:retrieve:168 - Pipeline hoan tat: 5 chunks cuoi cung.
2026-10-14 22:16:17 | INFO    | generator:generate_answer:47 - Đang gửi prompt đến LLM để sinh câu trả lời cho query: 'Trong tập dữ liệu Customer Shopping Behavior, có cột nào ghi thông tin về số điện thoại của khách hàng không?'
2026-10-14 22:16:32 | INFO    | rag_pipeline:query:75 - Hoàn tất xử lý RAG Pipeline trong 14.91s

Evaluating RAG: 100%|██████████| 50/50 [14:29<00:00, 17.39s/query]

================================================================================
📊 BÁO CÁO ĐÁNH GIÁ CHẤT LƯỢNG HỆ THỐNG RAG
================================================================================

📌 RETRIEVAL_PERFORMANCE:
  • Total Answerable Queries          : 40
  • Hit Rate @ 1                      : 0.6000 (60.00%)
  • Hit Rate @ 3                      : 0.8250 (82.50%)
  • Hit Rate @ 5                      : 0.9000 (90.00%)
  • MRR (Mean Reciprocal Rank)        : 0.7133 (71.33%)
  • Context Recall                    : 0.8438 (84.38%)

📌 GENERATION_PERFORMANCE:
  • Mean Semantic Similarity (Cosine) : 0.7104 (71.04%)
  • Mean Answer Relevancy (LLM Judge) : 0.8360 (83.60%)
  • Mean Token F1-Score               : 0.3783 (37.83%)
  • Mean Token Precision              : 0.2968 (29.68%)
  • Mean Token Recall                 : 0.6474 (64.74%)
  • Exact Match Rate                  : 0.0500 (5.00%)

📌 ANTI_HALLUCINATION:
  • Total Unanswerable Queries        : 10
  • Correct Rejection Rate (Anti-Hallucination): 1.0000 (100.00%)
  • Hallucination Rate                : 0.0000 (0.00%)

📌 SYSTEM_LATENCY:
  • Total Evaluated Queries           : 50
  • Average Latency (seconds)         : 11.3435
  • Min Latency                       : 1.1438
  • Max Latency                       : 17.4693

📌 BREAKDOWN_BY_QUESTION_TYPE:
  • direct                            : {'Count': 30, 'Avg Hit@3': 0.8333, 'Avg Semantic Sim': 0.6802, 'Avg Relevancy (Judge)': 0.7667, 'Avg F1': 0.3848, 'Avg Latency (s)': 10.9}
  • reasoning                         : {'Count': 10, 'Avg Hit@3': 0.8, 'Avg Semantic Sim': 0.8011, 'Avg Relevancy (Judge)': 0.88, 'Avg F1': 0.3586, 'Avg Latency (s)': 10.12}
  • unanswerable                      : {'Count': 10, 'Avg Hit@3': 0.0, 'Avg Semantic Sim': 1.0, 'Avg Relevancy (Judge)': 1.0, 'Avg F1': 0.0, 'Avg Latency (s)': 13.91}
================================================================================

## 4. Bảng Kết quả Chi tiết Từng Câu hỏi

In [5]:
df_results = result.to_dataframe()
display(df_results[["id", "query", "hit@1", "hit@3", "mrr", "token_f1", "latency_seconds"]].head(10))

# Lưu kết quả ra file
result.save_json(root / "data" / "eval" / "evaluation_results_no_rerank_hybrid.json")
result.save_csv(root / "data" / "eval" / "evaluation_details_no_rerank_hybrid.csv")
print("✅ Đã lưu kết quả đánh giá vào data/eval/")

,id,query,hit@1,hit@3,mrr,token_f1,latency_seconds
0,q001,Đề tài so sánh hiệu năng của hai mô hình nào t...,1.0,1.0,1.0,0.235294,2.926712
1,q002,Bài toán phân loại ảnh X-quang nha khoa trong ...,1.0,1.0,1.0,0.432432,1.143789
2,q003,Tập dữ liệu được sử dụng trong đồ án được lấy ...,1.0,1.0,1.0,0.380952,2.516855
3,q004,"Số lượng ảnh trong tập train, valid và test củ...",1.0,1.0,1.0,0.888889,1.583305
4,q005,Kiến trúc DenseNet201 được chia thành bao nhiê...,0.0,1.0,0.5,0.500000,10.099216
5,q006,Growth Rate (k) thường dùng trong DenseNet201 ...,1.0,1.0,1.0,0.266667,13.527914
6,q007,Mô hình nào đạt độ chính xác trên tập test cao...,1.0,1.0,1.0,0.093750,14.064105
7,q008,Mô hình DenseNet201 đạt kết quả tốt nhất tại e...,1.0,1.0,1.0,0.000000,12.442998
8,q009,Phương pháp tiền xử lý ảnh đơn lẻ nào có tỷ lệ...,1.0,1.0,1.0,0.700000,11.634785
9,q010,Vì sao nhóm nghiên cứu chọn DenseNet201 làm mô...,1.0,1.0,1.0,0.446429,2.786612

2026-10-14 22:17:32 | INFO    | rag_evaluator:save_json:77 - Đã lưu kết quả đánh giá JSON tại: E:\Personal Project\vietnamese-rag\data\eval\evaluation_results_no_rerank_hybrid.json
2026-10-14 22:17:32 | INFO    | rag_evaluator:save_csv:85 - Đã lưu bảng chi tiết CSV tại: E:\Personal Project\vietnamese-rag\data\eval\evaluation_details_no_rerank_hybrid.csv
✅ Đã lưu kết quả đánh giá vào data/eval/

## 5. Thử nghiệm So sánh: Có Reranker vs Không có Reranker

In [ ]:
# Đánh giá khi TẮT Reranker (chỉ dùng Dense Search)
result_no_rerank = evaluator.evaluate(
    dataset=dataset,
    top_k=3, # Lấy thẳng top 3 từ Vector DB
    use_rerank=False,
)

compare_df = pd.DataFrame([
    {
        "Cấu hình": "Có Reranker (BGE-M3 + Rerank Top 3)",
        "Hit@1": result.summary["retrieval_performance"]["Hit Rate @ 1"],
        "Hit@3": result.summary["retrieval_performance"]["Hit Rate @ 3"],
        "MRR": result.summary["retrieval_performance"]["MRR (Mean Reciprocal Rank)"],
        "Context Recall": result.summary["retrieval_performance"]["Context Recall"],
        "Avg Latency (s)": result.summary["system_latency"]["Average Latency (seconds)"],
    },
    {
        "Cấu hình": "Không Reranker (Chỉ Vector Search Top 3)",
        "Hit@1": result_no_rerank.summary["retrieval_performance"]["Hit Rate @ 1"],
        "Hit@3": result_no_rerank.summary["retrieval_performance"]["Hit Rate @ 3"],
        "MRR": result_no_rerank.summary["retrieval_performance"]["MRR (Mean Reciprocal Rank)"],
        "Context Recall": result_no_rerank.summary["retrieval_performance"]["Context Recall"],
        "Avg Latency (s)": result_no_rerank.summary["system_latency"]["Average Latency (seconds)"],
    }
])

display(compare_df)

In [ ]:
from IPython.display import display, Markdown

refused_ids = [ "q032", "q035", "q037", "q042", "q044"]


def _get(obj, key, default=None):
    """Lấy giá trị từ dict hoặc object."""
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


# Lấy danh sách details từ result (hỗ trợ cả 2 dạng)
details = _get(result, "details", []) or []
# Build dict id -> detail để tra cứu nhanh
detail_map = {_get(d, "id"): d for d in details}


for sample in dataset:
    if sample.id not in refused_ids:
        continue

    chunks = pipeline.retrieval_pipeline.retrieve(
        query=sample.query,
        top_k=10,
        top_n=3,
        use_rerank=True,
        use_hybrid=True,
    )

    # Lấy model answer từ detail tương ứng
    detail = detail_map.get(sample.id)
    model_answer = _get(detail, "generated_answer", "<không có>") if detail else "<không có>"

    md = [f"##  {sample.id}: {sample.query}\n"]
    md.append(f"**Ground truth:** `{sample.ground_truth}`\n")
    md.append(f"** Model trả lời:** `{model_answer}`\n")
    md.append("---\n")

    for i, c in enumerate(chunks, 1):
        # Lấy metadata và text
        if isinstance(c, dict):
            meta = c.get("metadata", {}) or {}
            text = c.get("text", "") or meta.get("text", "")
        else:
            meta = getattr(c, "metadata", {}) or {}
            if not isinstance(meta, dict):
                meta = getattr(meta, "__dict__", {})
            text = (getattr(c, "text", "") or
                    getattr(c, "content", "") or
                    meta.get("text", ""))

        page = meta.get("page_number", "?")
        md.append(f"### 📄 Chunk {i} | page={page}")
        md.append(f"```\n{str(text).strip()}\n```\n")

    display(Markdown("\n".join(md)))

2026-10-11 22:29:50 | INFO    | retrieval_pipeline:retrieve:59 - Retrieval Pipeline cho query: 'Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?' (hybrid=True, rerank=True, top_k=10, top_n=3)
2026-10-11 22:29:50 | INFO    | hybrid_retriever:retrieve:33 - Bắt đầu Hybrid Search: 'Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?' (dense_w=0.6, sparse_w=0.4)
2026-10-11 22:29:50 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?' (top_k=10)
2026-10-11 22:29:50 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-11 22:29:50 | INFO    | hybrid_retriever:retrieve:103 - Hoàn tất Hybrid Search. Trả về 10 chunks.
2026-10-11 22:29:50 | INFO    | reranker:rerank:61 - Bắt đầu Reranking cho 10 chunks với câu hỏi: 'Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?' (top_n=3)
2026-10-11 22:29:54 | INFO    | reranker:rerank:85 - Hoàn tất Reranking. Lọc lại top 3 chunks chất lượng nhất.

## 🆔 q031: Số lượng ảnh lớp Implant trong tập test của bộ dữ liệu là bao nhiêu?

**🎯 Ground truth:** `104 ảnh.`

**❌ Model trả lời:** `<không có>`

---

### 📄 Chunk 1 | page=?
```
Về phân bố dữ liệu giữa các lớp, có thể thấy sự chênh lệch rất lớn. Lớp Normal chiếm ưu thế vượt trội với 17.400 ảnh trong tập huấn luyện, trong khi lớp Cavity chỉ có 576 ảnh và lớp Impacted Tooth chỉ có 428 ảnh. Tỉ lệ mất cân bằng giữa lớp nhiều nhất và ít nhất lên tới khoảng 30:1. Sự mất cân bằng này cũng thể hiện rõ ở trên tập valid và test, với lớp Normal có 1.941 ảnh (tập valid) và 1.241 ảnh (tập test), trong khi Cavity chỉ có 43 và 22 ảnh tương ứng.
```

### 📄 Chunk 2 | page=?
```
│ ├── Impacted Tooth/

│ ├── Implant/

│ ├── Normal/

│

│── test/

│ ├── Cavity/

│ ├── Fillings/

│ ├── Impacted Tooth/

│ ├── Implant/

│ ├── Normal/

Chi tiết tập dữ liệu:

*Bảng (thuộc: Tập dữ liệu)*
 | train | valid | test
--- | --- | --- | ---
Cavity | 576 | 43 | 22
Fillings | 5242 | 540 | 315
Impacted Tooth | 428 | 38 | 32
Implant | 1784 | 159 | 104
Normal | 17.4k | 1941 | 1241
Total | 25136 | 2812 | 1649

Bảng 1: Bảng mô tả chi tiết số lượng dữ liệu của dataset
```

### 📄 Chunk 3 | page=?
```
Bảng 1: Bảng mô tả chi tiết số lượng dữ liệu của dataset

Tập dữ liệu được tổ chức theo từng thư mục, mỗi thư mục đại diện cho một lớp tình trạng cần phân loại và chứa các ảnh X-quang tương ứng. Dữ liệu được chia thành ba tập huấn luyện (train), đánh giá (valid) và kiểm tra (test). Tổng số lượng ảnh trong tập huấn luyện là 25.136 ảnh, tập xác nhận là 2.812 ảnh và tập kiểm tra là 1.649 ảnh.
```

2026-10-11 22:29:54 | INFO    | retrieval_pipeline:retrieve:59 - Retrieval Pipeline cho query: 'Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?' (hybrid=True, rerank=True, top_k=10, top_n=3)
2026-10-11 22:29:54 | INFO    | hybrid_retriever:retrieve:33 - Bắt đầu Hybrid Search: 'Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?' (dense_w=0.6, sparse_w=0.4)
2026-10-11 22:29:54 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?' (top_k=10)
2026-10-11 22:29:54 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-11 22:29:54 | INFO    | hybrid_retriever:retrieve:103 - Hoàn tất Hybrid Search. Trả về 10 chunks.
2026-10-11 22:29:54 | INFO    | reranker:rerank:61 - Bắt đầu Reranking cho 10 chunks với câu hỏi: 'Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?' (top_n=3)
2026-10-11 22:29:58 | INFO    | reranker:rerank:85 - Hoàn tất Reranking. Lọc lại top 3 chunks chất lượng nhất.

## 🆔 q032: Accuracy trên tập train của DenseNet201 tại epoch 35 là bao nhiêu?

**🎯 Ground truth:** `0.9597 (95.97%).`

**❌ Model trả lời:** `<không có>`

---

### 📄 Chunk 1 | page=?
```
Mô hình EfficientNetB0 cho thấy tốc độ hội tụ nhanh hơn DenseNet201, chỉ sau 10 epoch mà accuracy trên tập train đã đạt gần 90% nhưng val_loss vẫn còn khá cao. Ở epoch thứ 15 có thể thấy ReduceLROnPlateau đã kích hoạt để giảm tốc độ học xuống còn 1e-5 giúp val_loss bắt đầu ổn định và giảm sâu. Đến epoch 25 có thể thấy accuracy trên tập val đạt gần 90% và val_loss chỉ còn 0.3696 cho thấy mô hình đang được học tốt. Và kết quả cho thấy mô hình có val_loss tốt nhất tại eopch thứ 26.
```

### 📄 Chunk 2 | page=?
```
Kết quả thực nghiệm cho thấy kiến trúc DenseNet201 thể hiện sự ưu việt với độ chính xác (Accuracy) đạt 93% và giá trị mất mát (Loss) dừng ở mức 0.27. Chỉ số Loss thấp phản ánh sự hội tụ ổn định của mạng, cho thấy sai số giữa giá trị dự đoán và nhãn thực tế đã được tối thiểu hóa hiệu quả. Với độ chính xác 93%, DenseNet201 chứng minh khả năng trích xuất các đặc trưng hình thái phức tạp trên ảnh X-quang nha khoa là rất đáng tin cậy.
```

### 📄 Chunk 3 | page=?
```
Mô hình kết thúc tại epoch 46 do cơ chế EarlyStopping với patience là 20, và kết quả đạt được cho thấy mô hình tốt nhất tại epoch thứ 26 với accuracy trên tập test là hơn 90% và val loss chỉ còn 0.3375. Có thể thấy hiệu suất và độ hội tụ của EfficientNetB0 thấp hơn DenseNet201.
```

2026-10-11 22:29:58 | INFO    | retrieval_pipeline:retrieve:59 - Retrieval Pipeline cho query: 'Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?' (hybrid=True, rerank=True, top_k=10, top_n=3)
2026-10-11 22:29:58 | INFO    | hybrid_retriever:retrieve:33 - Bắt đầu Hybrid Search: 'Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?' (dense_w=0.6, sparse_w=0.4)
2026-10-11 22:29:58 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?' (top_k=10)
2026-10-11 22:29:58 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-11 22:29:58 | INFO    | hybrid_retriever:retrieve:103 - Hoàn tất Hybrid Search. Trả về 10 chunks.
2026-10-11 22:29:58 | INFO    | reranker:rerank:61 - Bắt đầu Reranking cho 10 chunks với câu hỏi: 'Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?' (top_n=3)
2026-10-11 22:30:01 | INFO    | reranker:rerank:85 - Hoàn tất Reranking. Lọc lại top 3 chunks chất lượng nhất.

## 🆔 q033: Theo Bảng 6, lớp nào có chỉ số Precision cao nhất trên tập test?

**🎯 Ground truth:** `Lớp Normal với Precision 0.97.`

**❌ Model trả lời:** `<không có>`

---

### 📄 Chunk 1 | page=?
```
Về phân bố dữ liệu giữa các lớp, có thể thấy sự chênh lệch rất lớn. Lớp Normal chiếm ưu thế vượt trội với 17.400 ảnh trong tập huấn luyện, trong khi lớp Cavity chỉ có 576 ảnh và lớp Impacted Tooth chỉ có 428 ảnh. Tỉ lệ mất cân bằng giữa lớp nhiều nhất và ít nhất lên tới khoảng 30:1. Sự mất cân bằng này cũng thể hiện rõ ở trên tập valid và test, với lớp Normal có 1.941 ảnh (tập valid) và 1.241 ảnh (tập test), trong khi Cavity chỉ có 43 và 22 ảnh tương ứng.
```

### 📄 Chunk 2 | page=?
```
Lớp Fillings (Hàn răng) và Implant: Có kết quả ổn định với số lượng dự đoán đúng chiếm đa số (lần lượt là 291 và 94 mẫu).

Lớp Cavity (Sâu răng) và Impacted Tooth (Răng khôn mọc ngầm): Đây là hai lớp có số lượng mẫu ít hơn và tỷ lệ nhận diện đúng còn khiêm tốn, cần lưu ý đặc biệt.

Các sai số đáng chú ý
```

### 📄 Chunk 3 | page=?
```
Mô hình kết thúc tại epoch 46 do cơ chế EarlyStopping với patience là 20, và kết quả đạt được cho thấy mô hình tốt nhất tại epoch thứ 26 với accuracy trên tập test là hơn 90% và val loss chỉ còn 0.3375. Có thể thấy hiệu suất và độ hội tụ của EfficientNetB0 thấp hơn DenseNet201.
```

2026-10-11 22:30:01 | INFO    | retrieval_pipeline:retrieve:59 - Retrieval Pipeline cho query: 'Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.' (hybrid=True, rerank=True, top_k=10, top_n=3)
2026-10-11 22:30:01 | INFO    | hybrid_retriever:retrieve:33 - Bắt đầu Hybrid Search: 'Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.' (dense_w=0.6, sparse_w=0.4)
2026-10-11 22:30:01 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.' (top_k=10)
2026-10-11 22:30:01 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-11 22:30:01 | INFO    | hybrid_retriever:retrieve:103 - Hoàn tất Hybrid Search. Trả về 10 chunks.
2026-10-11 22:30:01 | INFO    | reranker:rerank:61 - Bắt đầu Reranking cho 10 chunks với câu hỏi: 'Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.' (top_n=3)
2026-10-11 22:30:04 | INFO    | reranker:rerank:85 - Hoàn tất Reranking. Lọc lại top 3 chunks chất lượng nhất.

## 🆔 q037: Dựa vào Bảng 4 và Bảng 5, hãy so sánh tốc độ hội tụ của DenseNet201 và EfficientNetB0.

**🎯 Ground truth:** `EfficientNetB0 hội tụ nhanh hơn ở giai đoạn đầu (chỉ sau 10 epoch đã đạt accuracy train ~90%), nhưng DenseNet201 đạt giá trị val_acc cao hơn ở các epoch cuối (92.78% so với 90.37% của EfficientNetB0) và có val_loss thấp hơn (0.2997 so với 0.3629).`

**❌ Model trả lời:** `<không có>`

---

### 📄 Chunk 1 | page=?
```
Trong khi đó, mô hình EfficientNetB0 đạt điểm tối ưu tại Epoch thứ 26 với độ chính xác trên tập kiểm thử là 91% và giá trị Validation Loss là 0.34. Khi đặt lên bàn cân so sánh, DenseNet201 cho thấy hiệu suất vượt trội hơn về cả khả năng phân loại lẫn tốc độ hội tụ. Sự khác biệt này bắt nguồn từ đặc thù kiến trúc: DenseNet201 với cấu trúc 201 lớp cùng cơ chế kết nối dày đặc (Dense Blocks) cho phép tái sử dụng đặc trưng xuyên suốt các tầng, giúp mô hình học được các chi tiết ở nhiều cấp độ phân giải khác nhau
```

### 📄 Chunk 2 | page=?
```
Mô hình EfficientNetB0 cho thấy tốc độ hội tụ nhanh hơn DenseNet201, chỉ sau 10 epoch mà accuracy trên tập train đã đạt gần 90% nhưng val_loss vẫn còn khá cao. Ở epoch thứ 15 có thể thấy ReduceLROnPlateau đã kích hoạt để giảm tốc độ học xuống còn 1e-5 giúp val_loss bắt đầu ổn định và giảm sâu. Đến epoch 25 có thể thấy accuracy trên tập val đạt gần 90% và val_loss chỉ còn 0.3696 cho thấy mô hình đang được học tốt. Và kết quả cho thấy mô hình có val_loss tốt nhất tại eopch thứ 26.
```

### 📄 Chunk 3 | page=?
```
Mô hình kết thúc tại epoch 46 do cơ chế EarlyStopping với patience là 20, và kết quả đạt được cho thấy mô hình tốt nhất tại epoch thứ 26 với accuracy trên tập test là hơn 90% và val loss chỉ còn 0.3375. Có thể thấy hiệu suất và độ hội tụ của EfficientNetB0 thấp hơn DenseNet201.
```

2026-10-11 22:30:04 | INFO    | retrieval_pipeline:retrieve:59 - Retrieval Pipeline cho query: 'Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?' (hybrid=True, rerank=True, top_k=10, top_n=3)
2026-10-11 22:30:04 | INFO    | hybrid_retriever:retrieve:33 - Bắt đầu Hybrid Search: 'Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?' (dense_w=0.6, sparse_w=0.4)
2026-10-11 22:30:04 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?' (top_k=10)
2026-10-11 22:30:04 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-11 22:30:04 | INFO    | hybrid_retriever:retrieve:103 - Hoàn tất Hybrid Search. Trả về 10 chunks.
2026-10-11 22:30:04 | INFO    | reranker:rerank:61 - Bắt đầu Reranking cho 10 chunks với câu hỏi: 'Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?' (top_n=3)
2026-10-11 22:30:07 | INFO    | reranker:rerank:85 - Hoàn tất Reranking. Lọc lại top 3 chunks chất lượng nhất.

## 🆔 q042: Theo kết quả phân tích ở Chương 2, gói thành viên nào chiếm tỷ trọng lớn nhất với 40.6% trong tập dữ liệu Fitness?

**🎯 Ground truth:** `Gói Premium với 40.6%.`

**❌ Model trả lời:** `<không có>`

---

### 📄 Chunk 1 | page=23
```
Biểu đồ thể hiện cơ cấu loại thẻ thành viên (Basic, Standard, Premium,
Elite) theo từng thành phố. Có sự khác biệt rõ rệt về tỷ lệ lựa chọn gói tập giữa
các địa phương. Gói Premium chiếm tỷ lệ cao nhất ở hầu hết các thành phố, đặc
biệt nổi bật tại San Jose (54%), Bakersfield (51%) và San Francisco (40%). Gói
Standard phổ biến nhất tại Fresno (33%), Oakland (31%) và Long Beach (34%),
nhưng lại thấp nhất tại San Jose (19%) và Bakersfield (19%). Gói Elite tuy có tỷ
```

### 📄 Chunk 2 | page=20
```
Biểu đồ cho thấy cơ cấu thành viên tương đối ổn định, trong đó hai hạng
thẻ (vàng) và (đỏ) luôn chiếm ưu thế với hơn 60% tỷ trọng ở
```

### 📄 Chunk 3 | page=12
```
## 1.2 MỤC TIÊU ĐỒ ÁN
Để đảm bảo tính khoa học, chuyên nghiệp và khẳng định chất lượng đầu ra
của dự án, nhóm chúng em đã xác định lộ trình triển khai cụ thể qua các giai đoạn
từ xử lý dữ liệu đến xây dựng mô hình thực tiễn. Mục tiêu trọng tâm là khai thác
tối đa giá trị từ 2 tập dữ liệu Fitness Membership và Customer Shopping
Behavior nhằm đưa ra các giải pháp tối ưu hóa trải nghiệm khách hàng và hỗ trợ
quyết định kinh doanh. Cụ thể, các mục tiêu chi tiết được thiết lập như sau:
```

2026-10-11 22:30:07 | INFO    | retrieval_pipeline:retrieve:59 - Retrieval Pipeline cho query: 'Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?' (hybrid=True, rerank=True, top_k=10, top_n=3)
2026-10-11 22:30:07 | INFO    | hybrid_retriever:retrieve:33 - Bắt đầu Hybrid Search: 'Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?' (dense_w=0.6, sparse_w=0.4)
2026-10-11 22:30:07 | INFO    | vector_retriever:retrieve:49 - Bắt đầu tìm kiếm vector cho câu hỏi: 'Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?' (top_k=10)
2026-10-11 22:30:07 | INFO    | vector_retriever:retrieve:90 - Đã tìm thấy 10 chunks tương đồng từ Qdrant.
2026-10-11 22:30:08 | INFO    | hybrid_retriever:retrieve:103 - Hoàn tất Hybrid Search. Trả về 10 chunks.
2026-10-11 22:30:08 | INFO    | reranker:rerank:61 - Bắt đầu Reranking cho 10 chunks với câu hỏi: 'Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?' (top_n=3)
2026-10-11 22:30:10 | INFO    | reranker:rerank:85 - Hoàn tất Reranking. Lọc lại top 3 chunks chất lượng nhất.

## 🆔 q044: Quy tắc gán nhãn trong bài toán phân loại churn hội viên Fitness được thực hiện như thế nào?

**🎯 Ground truth:** `Lớp 0 (Đang dùng): Hội viên ghé thăm trong vòng dưới 21 ngày, đại diện cho nhóm đang hoạt động ổn định (35.3%). Lớp 1 (Có nguy cơ): Hội viên không đến từ 21 đến dưới 45 ngày, thuộc nhóm có nguy cơ rời bỏ cần chăm sóc (39.6%). Hội viên ngừng đến trên 45 ngày, được xác định là đã rời bỏ dịch vụ (25.1%).`

**❌ Model trả lời:** `<không có>`

---

### 📄 Chunk 1 | page=63
```
# A. Gán nhãn cho dữ liệu
Để đào sâu hơn tập dữ liệu, không chỉ phân tích và khai thác ở bài toán phân cụm
nhóm em còn phân tích khám phá sang bài toán phân loại. Trước hết, nhóm
chúng em đã thực hiện bước dán nhãn mục tiêu nhằm xác định chân dung khách
hàng tiềm năng. Vì tập dữ liệu gốc chưa có sẵn cột phân loại, nhóm đã xây dựng
một bộ quy tắc định tính dựa trên ba yếu tố cốt lõi: sự cam kết (Subscription),
kinh nghiệm mua sắm (Previous Purchases) và mức độ hài lòng (Review Rating).
```

### 📄 Chunk 2 | page=37
```
# A. Gán nhãn cho dữ liệu
Vì tập dữ liệu ban đầu không có cột nhãn trực tiếp cho biết khách hàng đã
rời bỏ dịch vụ hay chưa, chúng em thực hiện gán nhãn dựa trên hành vi thực tế
của khách hàng.
Quá trình gán nhãn được thực hiện thông qua việc tính toán khoảng thời
gian biến động giữa ngày ghi nhận cuối cùng trong hệ thống (ngày tham chiếu:
22/07/2025) và ngày ghé thăm phòng tập gần nhất của từng khách hàng
(last_visit_date). Dựa trên thuộc tính days_since_last_visit vừa được trích xuất,
```

### 📄 Chunk 3 | page=71
```
phản ánh hành vi khách hàng chính xác và kịp thời hơn đáng kể.
Về ứng dụng kinh doanh , bước phát triển quan trọng nhất là triển khai các
mô hình này thành hệ thống vận hành thực tế. Cụ thể, mô hình phân loại Churn
(Fitness) có thể được tích hợp vào hệ thống CRM để tự động kích hoạt quy trình
chăm sóc khách hàng theo ngưỡng rủi ro hàng tuần. Đối với bài toán phân loại
khách hàng tiềm năng (Shopping), mô hình có thể được nhúng vào pipeline
```